### ISSUE TITLE
Kakoune waits on shell script, rarely gets data from xdebug

### ISSUE THREAD

**Issue by in0ni** [JJK96/kakoune_dbgp#4]
Hello @JJK96,

I have been trying to get this plugin working for a couple of hours. I am able to start the debug session, connect to it (using browser plugin), and I see commands being sent to the input_pipe. I can set a breakpoint, but only twice has it actually show the indicator that an breakpoint is placed. The rest of the times I get no feedback in Kakoune.

Often the plugin freezes the editor, sometimes with the message 'waiting for script' others (when setting breakpoints) nothing. I have noticed that tailing the input_pipe file solves that issue.

I think it might be due to running lando. On VScode, which I am using solely for debugging, a path has to be mapped /app/ -> /project-dir.

Any ideas? Is there anyway you might be able to help me troubleshoot this issue, see if I can get it working?

Thanks in advance

**Comment by JJK96** [comment]
Hey,  you for your interest in the plugin. I have to admit that I have not been using this plugin for quite some time, so I'd have to read up on how dbgp and this plugin works again... 
Maybe the plugin is also not up to date on the latest dbgp version, can you check if there has been a release of dbgp since the latest commit?
I'll try to help you debug, but I currently don't have a machine where it is installed...
Nowadays I use VS Code for debugging, because I think a GUI is a great benefit for debugging

**Comment by JJK96** [comment]
If lando is sort of similar to docker, it might be that dbgp cannot find the debugged file and that it hangs on that. I'll have to check how you can point dbgp to the right directory

**Comment by in0ni** [comment]
Yes, lando actually uses docker -- so that has to be it. In docker it's /app/ so, I think I can check the source -- I assume I just need to ensure the project directory is replaced by file:///app/ -- right?

**Comment by JJK96** [comment]
I'm thinking about the freezing issue you mention, If tailing the input_fifo resolves the issue, then this means that the python file might somehow have exited, can you start it manually and see what happens?

**Comment by JJK96** [comment]
I don't see the project dir being set in this plugin, so I think you have to configure that in xdebug itself.

Also, have you enabled debugging in the python program? That might help in seeing what is going wrong

**Comment by in0ni** [comment]
Hello @JJK96,

Yeah, I tried to look into this in plugin source, but no luck. I actually found another plugin which I have working, so on my end -- with such a specific use case, no longer need.

Thanks for your time!

**Comment by JJK96** [comment]
Glad you found a solution, I'm curious, which plugin did you use in the end?

**Comment by in0ni** [comment]
https://github.com/jdugan6240/kak-dap :)

**Comment by JJK96** [comment]
Sounds like a better solution than this one 👌
